### ISSUE TITLE
Build with Stisla

### ISSUE THREAD

**Issue by nauvalazhar** [stisla/stisla#1]
Hi, if you have made something with Stisla. Reply this issue and put the link.

Thank you

**Comment by SunDi3yansyah** [comment]
Hi @nauvalazhar

My advice, use the wiki for this case

**Comment by nauvalazhar** [comment]
Ok, OTW

**Comment by Mr-Kinan** [comment]
I love stisla
Thanks 

my project is a url shortener:
[http://www.url1is.com](http://www.url1is.com)

**Comment by anggablangkon** [comment]
Wooow, kereeen.
