### ISSUE TITLE
.form-control-sm not working on select form?

### ISSUE THREAD

**Issue by priatmoko** [stisla/stisla#102]
It is an awesome template. I try to migrate some web apps to use this template.
I found that form sizing not working on form select. It has same size as .form-control-md.
`
<select class="form-control form-control-sm">
                        <option>Option 1</option>
                        <option>Option 2</option>
                        <option>Option 3</option>
 </select>`

Thanks

maturnuwun, atau jangan2 saya yang kurang teliti ya?
:D

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Yes, you're right. This bug is due to CSS specificity. But, you can fix it with this code:
```
.form-control-sm {
    height: calc(1.8125rem + 2px) !important;
}
```
I know this is just a quick solution, not a good one.

**Comment by priatmoko** [comment]
thank you for the fast response and solution.
good luck to you
:D
