### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by polynar** [stisla/stisla#13]
Can you make nicescroll passive?

Edit
I got three of them in my console and if i open notifications or messages dropdown i get more.
![screenshot 2019-02-14 09 51 45](https://user-images.githubusercontent.com/1795922/52774711-2ba74980-303e-11e9-88f8-844eda836d2c.png)

**Comment by nauvalazhar** [comment]
Back to basic. Do we need NiceScroll? I plan to remove or replace it with another one. Too much NiceScroll I don't think it's so good.

**Comment by polynar** [comment]
I agree with you.

**Comment by nauvalazhar** [comment]
GitLab had a good conversation about this
https://gitlab.com/gitlab-org/gitlab-ce/issues/15664

**Comment by polynar** [comment]
Can you do it based on this: https://gitlab.com/gitlab-org/gitlab-ce/commit/c2a8daf9928439114ed4125577d376b76460d023 ?

**Comment by nauvalazhar** [comment]
I can just delete NiceScroll, but, will using the default scrollbar look good?

**Comment by polynar** [comment]
No, I don't think so, i search a sulution for it.
