### ISSUE TITLE
Add layout skins

### ISSUE THREAD

**Issue by MuhammadDicky** [stisla/stisla#135]
I recently add style **layout skins** for more options for users to choose what **layout skin** they prefer. I also add floating button for change **layout skin**, so users can see all **layout skins** trough all page.

This is some progress i have been made.
![stisla-layout-skins](https://user-images.githubusercontent.com/25713287/70819473-4fc7e880-1e11-11ea-867f-1c8c3f82ebaa.png)
![stisla-layout-skins-2](https://user-images.githubusercontent.com/25713287/70819474-4fc7e880-1e11-11ea-839c-8210bcf6438c.png)

If you want i can continue and create **PR** when this ready.

**Comment by nauvalazhar** [comment]
Wow. Can you show me the code and live preview link?

**Comment by muhammaddicky** [comment]
@nauvalazhar For now, is still on my local and working some other components, i have to check every components on every page to make sure i dont miss some components.

**Comment by muhammaddicky** [comment]
@nauvalazhar You can check may progress [here](https://codepen.io/muhammad_dicky/full/gObwwQv) for now.

**Comment by nauvalazhar** [comment]
Looks great. But, what about the button variations, alert and some other components? I mean, let's say we use green skin, it will definitely cause color conflicts with `success`. But, conceptually, I like what you make.

**Comment by muhammaddicky** [comment]
@nauvalazhar That is what user must decided if user want to use this style or we set up alternative color for conflict skin, so when user change skin all element that have conflict color will change to alternative color.

**Comment by nauvalazhar** [comment]
Interesting. I think we need to have several variables in the skin file, one of which is to adjust the color. And also makes it easier for developers to make their own skin color.

**Comment by muhammaddicky** [comment]
Yeah, or just one alternative color maybe enough because conflict only happen to one color right. I'm also already create mixin where user can choose what components and skin that user wanna compile.

**Comment by nauvalazhar** [comment]
Great. Can't wait to see it finish.

**Comment by muhammaddicky** [comment]
Yeah, you can update this issue by assign me for it.

**Comment by GerryGe** [comment]
@muhammaddicky Great work! Can't wait to see it finish. Do you have any plan to finish this feature?

**Comment by muhammaddicky** [comment]
@GerryGe Yes, but now as you can see is still not on production because i recently focus on mobile so i'm really sorry if this can be push earlier. But i'm already finish some components and i try to make another developer easy to use it when they wanna make their own custom layout skins.

**Comment by GerryGe** [comment]
Yes, understood, please go ahead.

**Comment by adistoica** [comment]
hi @MuhammadDicky!

do you have any updates on this?
