### ISSUE TITLE
Select Group Button doesn't unselect properly

### ISSUE THREAD

**Issue by killua-eu** [stisla/stisla#138]
See problem at https://demo.getstisla.com/forms-advanced-form.html `Select Group Button -> Your skills` 

To reproduce:

- Click "CSS"
- Click "CSS" again

Expected behavior: CSS will get unselected.
Visible behavior: CSS remains selected on clicking. Deselects only after you click any other option.

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. This issue has been resolved by this pull request (#111).
