### ISSUE TITLE
Suggestion - basic requirements related to current template trends

### ISSUE THREAD

**Issue by Jewinn** [stisla/stisla#142]
I would first congratulate you for such an amazing Template that ever build open source.

additionally, I would like to suggest some modern template trends that are being most catchable for developers are,

- main theme color customization(may you suggest direct changes on files in the documentation)
- Navigation customization options (like fixed navigation and fixed logo instead of scrolling one, may as an additional option)
- you have made chat page but it includes cards that are basically nonusable, it should be as chat popup and another chat page would be as >> https://cutt.ly/SrxDbuI (see at its responsive nature and function, also its in full height with no scrollable content page)

![Screenshot (115)_LI](https://user-images.githubusercontent.com/59877371/72354778-572e2a80-370c-11ea-8578-88a68ff2d869.jpg)

also, these chat pages are common in most templates and they are very useful for developers.

best of luck for more downloads in the future!

Regards,
Jewin

**Comment by nauvalazhar** [comment]
Hi, thank you for your suggestion. I'll note your suggestion.
