### ISSUE TITLE
Master file nodepackage install problem

### ISSUE THREAD

**Issue by Jewinn** [stisla/stisla#143]
Please provide documentation for development by sass, step by step it also going to help for developers and contributors.
setup for development including which platform for development you are using.

**Comment by muhammaddicky** [comment]
@Jewinn It's use gulp for development including for compiling sass and gulp already setup in this repo, you just need to play on sass file.

**Comment by Jewinn** [comment]
will I get some documentation about that,
what are the steps that everyone needs to follow from downloading files to install dependancies and all other kinds of stuff?

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting this issue. I apologize for the bad documentation. But, you can follow the steps in this Readme repository. https://github.com/stisla/stisla#quick-start

Simply, you need to install Yarn instead of NPM.

**Comment by Jewinn** [comment]
ok, I'm trying npm and that's the problem.
please mention the right guide in the readme!

**Comment by Jewinn** [comment]
there are lots of problems I'm facing right now, also stisla-dev not working. I would suggest you to make a small video for installation and complete development of 1-2 pages with minor changes in scss including compiling. it resolves problems for many of us. 
video reference:  example of keen theme https://www.youtube.com/watch?v=dqZLWuAEdJ8

**Comment by cyberhck** [comment]
@Jewinn it does say use yarn on documentation [here](https://github.com/stisla/stisla#quick-start) video isn't necessarily correct form of documentation

**Comment by Jewinn** [comment]
@cyberhck I'm getting errors will you help me with these?
