### ISSUE TITLE
Side bar menu does not display in mobile

### ISSUE THREAD

**Issue by Ahmadgoma** [stisla/stisla#148]
When i open from mobile, I can not find side menu.

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Can you show me the screenshot or an error message?

**Comment by Ahmadgoma** [comment]
Hey There @nauvalazhar  :
I used your template in my works but I found this bug after using stisla.
If you used mobile to access the dashboard built with stisla - on first render the side menu appear just for one second and it disappear suddenly.

![20200303_154400](https://user-images.githubusercontent.com/28639809/75781843-9cfb8c80-5d66-11ea-9de1-c07319badfef.jpg)
![20200303_154456](https://user-images.githubusercontent.com/28639809/75781855-a4bb3100-5d66-11ea-9370-636c80e91514.jpg)

**Comment by nauvalazhar** [comment]
Hi, thank you for sending the screenshots. It's not a bug, it's normal. I use JavaScript to hide the sidebar.

**Comment by Ahmadgoma** [comment]
Thank you for your response.
So is you made it for web only ? 
To close this issue.

**Comment by nauvalazhar** [comment]
No, that's the way I handle responsiveness in the sidebar.

**Comment by Ahmadgoma** [comment]
So, you should need to add drop down to show side bar if i use mobile device.

**Comment by LucasDshg** [comment]
How did you repair? I've the same problem here.
