### ISSUE TITLE
Ijin Penggunaan

### ISSUE THREAD

**Issue by hanzkid** [stisla/stisla#15]
Halo,
Saya bingung mau ijin dimana, karena saya lihat ini dari share facebook.
Saya ijin menggunakan template admin untuk program sekolah, ketentuan menurut mit license hanya mencantumkan credit, kalo boleh tahu, pencatumannya gimana ya?

**Comment by nauvalazhar** [comment]
Hi, 
Just copy the LICENSE file on your project.

**Comment by hanzkid** [comment]
Okay, thanks
