### ISSUE TITLE
Sidebar active class not working

### ISSUE THREAD

**Issue by H-eru** [stisla/stisla#151]
Sidebar active class is missing after click another dropdown sidebar menu
Already use class="main-sidebar sidebar-style-2" same as on the demo site

![st](https://user-images.githubusercontent.com/46050449/76821892-de4d6b00-6841-11ea-93e5-c437133e85b1.png)

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting this issue. Yes, this is a "bug". We haven't fixed it yet, if you want, you can make a pull request. Thank you!

**Comment by nauvalazhar** [comment]
Fixed!
