### ISSUE TITLE
Installation of Stisla

### ISSUE THREAD

**Issue by koossaayy** [stisla/stisla#153]
Hello, sorry if I'm annoying anyone. But it seems I can't install it properly. 
I'm not a front-end developer, but I ran the commands provided in the documentation, I can't locate the dist folder, also, the assets folders doesn't not have the "modules" folder like the demo. 
Am I doing something wrong here ? Or should I do it manually ? 
Thank you and Sorry again.

**Comment by nauvalazhar** [comment]
You need to install Yarn and run the `yarn` command in your project folder.
