### ISSUE TITLE
https://getstisla.com SSL error.

### ISSUE THREAD

**Issue by rama-adi** [stisla/stisla#157]
I just wanted to notify you that the main site https://getstisla.com has invalid certs.

**Comment by cyberhck** [comment]
@nauvalazhar it's using the expired let's encrypt certificate, it's time to renew (maybe use a cron job to  make sure it renewed every 5 days (only renew if it's about to expire)) :slightly_smiling_face:

**Comment by nauvalazhar** [comment]
Done
