### ISSUE TITLE
Stisla template shows a blank page in mobile view

### ISSUE THREAD

**Issue by Jaimeching** [stisla/stisla#160]
Hi everyone, i have this issue:

When i am at desktop the template shows good:

![image](https://user-images.githubusercontent.com/64601977/80731273-4c877d80-8ad0-11ea-88ff-eddc5e6e29ee.png)

but when i try to see the webpage in mobile view it shows me like this:
![image](https://user-images.githubusercontent.com/64601977/80731362-6c1ea600-8ad0-11ea-82b4-c84623857782.png)

Do you have any idea why this happen?

**Comment by nauvalazhar** [comment]
Is there any error message?
