### ISSUE TITLE
ChartJS not showing

### ISSUE THREAD

**Issue by ayobelajartech** [stisla/stisla#165]
I downloaded Stisla and I want to use it for my project. But, when I look up for charts in page "_pages/modules-chartjs.html_", only boxes and the titles are showing, and no charts. Can anybody help me to fix this issue?

**Comment by cyberhck** [comment]
did you install all dependencies? run `yarn`?

**Comment by ayobelajartech** [comment]
Yes, I did. I installed yarn through Scoop on my Windows PC.

**Comment by aacassandra** [comment]
halo kawan @ayobelajartech 

try to clone stisla from https://github.com/aacassandra/stisla
- git clone git@github.com:aacassandra/stisla.git
- npm i
- and you can try using live serve from visual studio code for testing
- and navigate to 'pages' directory

Hope it helps and thanks to all STISLA developers. hopefully more crazy
