### ISSUE TITLE
Google autofill hides the form validation check

### ISSUE THREAD

**Issue by Harshal96** [stisla/stisla#174]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/20720521/90705758-4bce4f00-e259-11ea-8caa-2a1b5bd61a09.png">

**Comment by Harshal96** [comment]
The check mark in the email is masked by google chrome autofill.

**Comment by nauvalazhar** [comment]
Hi, about this issue, you can refer to [this issue from Bootstrap](https://github.com/twbs/bootstrap/issues/21463).
