### ISSUE TITLE
Drawer not working with next/link

### ISSUE THREAD

**Issue by permanar** [stisla/stisla#175]
So I try to use this awesome template and convert it to React (Next.js) components.

And the main issue exist after I realize it whenever I use the Link component to redirect over any pages, the drawer became buggy (or at least what I currently know is just the drawer). But if I use the normal `a href` tag, everything happen to be working. But IMO, it is not worth to use `a href` tag instead of the Link component,

Sample code:
```
<Link href="/manage/"> 
   <a>Manage Data</a> 
</Link>
```
++++++++++++++++++++++
Video reference:
[GDrive](https://drive.google.com/file/d/1XYBpJmVWaLn98TXYaALxMRO8YMk60HEe/view)
++++++++++++++++++++++

This is my first time facing issue like this, is there any workaround? I don't even know either is this Stisla issue or Next.js bug.
Can someone help me for any solution?

**Comment by permanar** [comment]
I am not really sure and feel so sorry for tagging you @nauvalazhar but, can you help me with any little thing?

**Comment by nauvalazhar** [comment]
Hi, sorry for the late reply. I don't think it's a Stisla or Next.js bug. As far as I know Next.js is SSR by default. So, maybe it's a DOM issue, like the "event handler" being called twice, or the jQuery selector selecting an element while the DOM isn't fully loaded. So far I haven't tried Stisla with the SPA, so maybe I still don't know how to fix it. If you find a solution, maybe you can share it with us.
