### ISSUE TITLE
Is the repo still maintained ?

### ISSUE THREAD

**Issue by lilouch** [stisla/stisla#178]
Hi,

The website getstisla.com does not work anymore. Is the repo still maintained ? 

Thank

**Comment by rizkyyangpalsu** [comment]
That website still work. Right, this repo still maintenance.

**Comment by lilouch** [comment]
Any update for the new version @rizkyyangpalsu  ?

**Comment by zuramai** [comment]
This repo is still maintained and will be looking forward to Stisla v3.
