### ISSUE TITLE
My Modals are going wrong

### ISSUE THREAD

**Issue by sahilch186** [stisla/stisla#183]
I am a Beginner UI Developer working with HTML, CSS, JS, Bootstrap, etc. and Currently working on project where I am using Stisla Admin, the design is really awesome even client is loving it. **I am Facing issue with modal.** I need a fixed navbar so I have given `position: fixed; 
z-index: 899;`
to `.navbar` but know the modal is getting hidden behind the navbar where modal's z-index is
`z-index: 1050;`
Can someone help me please

**Comment by Nadeem-K** [comment]
@sahilch186  Place the modal outside <body>, this should solve the problem.  If you are using MVC model, use partial view to load the modal. ;)
