### ISSUE TITLE
Sidebar pops on every refresh of the page

### ISSUE THREAD

**Issue by trenaldas** [stisla/stisla#189]
Hello, first of all thanks for this awesome dashboard. I used laravel version of it and it really makes mine, as back-end developer, life easier. But I have an issue with sidebar. On every reload of the page it refreshes: when it's on small screen - mobile, pad, it pops out and then slides back in. And on the big screen it refreshes to, I mean auto slides out the sub-menus. I think it's all being done in toggleLayout function, just can't figure out how could I fix it. Thanks in advance

**Comment by DayoWong0** [comment]
add sidebar-gone class to body
