### ISSUE TITLE
An Avatar Image Doesn't Appear

### ISSUE THREAD

**Issue by glenaldinlim** [stisla/stisla#19]
Hello @nauvalazhar !
The Avatar Image Doesn't Appear in _Chat Box_ Page. I think the path is wrong.
I attached the screenshot, maybe this issue just on my computer. Thank you in advance!

![screenshot_2019-02-18 components chat box stisla](https://user-images.githubusercontent.com/35095375/52955635-bdf17980-33bf-11e9-9f5c-f4df941205a7.png)

**Comment by nauvalazhar** [comment]
Hi, the problem is in the `components-chat-box.js` file. Just fix the path to the right path. For example https://github.com/stisla/stisla/blob/master/dist/assets/js/page/components-chat-box.js#L42
