### ISSUE TITLE
How to use summernote editor

### ISSUE THREAD

**Issue by sanjaylama** [stisla/stisla#191]
I am confused!
I see that summernote is in the demo, but it does not seem to be in the downloaded template.
I am using it with laravel and I search it in the code as well, seems like  it has something like this
if(jQuery().summernote) {
    $(".summernote").summernote({
       dialogsInBody: true,
      minHeight: 250,
    });
    $(".summernote-simple").summernote({
       dialogsInBody: true,
      minHeight: 150,
      toolbar: [
        ['style', ['bold', 'italic', 'underline', 'clear']],
        ['font', ['strikethrough']],
        ['para', ['paragraph']]
      ]
    });
  }

but no files, and it is not working as well,
is it included,if now how can i use it or include it?

thanks

**Comment by permanar** [comment]
@sanjaylama 
What is the error? Could you provide more on how to reproduce the errors?
Have you make it sure that you already downloaded/have it all the dependencies needed?

**Comment by zuramai** [comment]
This issue is closed due to inactivity.
