### ISSUE TITLE
What do you expect in Stisla 3 (Bootstrap 5)?

### ISSUE THREAD

**Issue by nauvalazhar** [stisla/stisla#203]
Thank you for always supporting this little project. 

As the title said.

From me:
- Improve the documentation
- Not everyone uses NPM/Yarn (there's should be a pre-compiled version for conservative users)
- A new dashboard design
- No jQuery (so it's not difficult to adapt to frameworks like React)
- UI kit (not only admin template)
- Figma file would be cool

**Comment by nauvalazhar** [comment]
designing the dashboard is not that easy 😂 

![gambar](https://user-images.githubusercontent.com/14899175/119140978-f2f14880-ba6e-11eb-84f3-c256c55a2ae3.png)

**Comment by cyberhck** [comment]
For me, modular please,
Also TypeScript,

And if I want only navbar for example, it should only pull in navbar from bootstrap, and overwrite your values, BUT it shouldn't include button in this case, and if I import button, it shouldn't include navbar :)

**Comment by ma3ain** [comment]
Thank you for keeping updating Stisla.

The thing I want to see the most is support RTL support in the new version.

Best.

**Comment by raikasdev** [comment]
I personally like top navigation, have you thought how that would look?

**Comment by cyberhck** [comment]
I was just trying out a theme my friend bought (Landkit) which also is bootstrap5.

I absolutely hated the codebase, I found the design to be pretty nice, but the usage was shit.

I'm trying to use it in nextjs framework, now I'm having to import ALL css that I'll need into 1 styles.css and use that,

What I'd have liked is that me being able to import navbar only if I'm using navbar in a page,

If I'm in profile sign in page, there's no need for navbar in my case, why would I want to import that? That doesn't work.

I think while bootstrap is moving towards correct direction, it's not doing it fast enough, it doesn't do scss modules, which means nothing works.

Now I'm having to basically go without much optimization.

**Comment by owf18916** [comment]
integration with laravel 8.x would be cool !

**Comment by raikasdev** [comment]
> integration with laravel 8.x would be cool !

Personally I don't think making Stisla integrated with a framework, so as much people could use it.

**Comment by cyberhck** [comment]
no, there's no integration needed.

all we gotta do is release css modules for individual components, when you use css modules, it should work for any framework.

**Comment by ProjectLinde37** [comment]
> 
> 
> integration with laravel 8.x would be cool !

Keep Stisla clean - integration should be done by the developer who will use it.
And a php-framework has nothing to do with an good layout.

**Comment by ProjectLinde37** [comment]
> 
> 
> Thank you for always supporting this little project.
> 
> As the title said.
> 
> From me:
> 
>     * Improve the documentation
> 
>     * Not everyone uses NPM/Yarn (there's should be a pre-compiled version for conservative users)
> 
>     * A new dashboard design
> 
>     * No jQuery (so it's not difficult to adapt to frameworks like React)
> 
>     * UI kit (not only admin template)
> 
>     * Figma file would be cool

Pre-compiled versionis a must.
Keep is clean from jquery - Native javascript if needed - keep the same idea as BS5

**Comment by syahid246** [comment]
Stisla sangatlah bagus!
Tetapi ada beberapa elemen yang `box-shadow` nya terlalu berlebihan (Misalnya button), dan mengakibatkan elemen tersebut terlihat kabur.
Semoga saja di Stisla 3 ada update-an dengan warna yang lebih enak dipandang dan box-shadow yang tidak berlebihan.

**Comment by Aloha276** [comment]
Any news about Stisla 3 ?

Anyway thank you for the hard work you put in it, keep it up!

**Comment by rizkytegar** [comment]
excusme, can this theme be used for my commercial project? and how much does it cost to use this theme in my commercial project?

**Comment by eerison** [comment]
Maybe this issue should be reopen?

**Comment by rizkytegar** [comment]
> Maybe this issue should be reopen?

yes

**Comment by holiq** [comment]
Any update for stisla 3?
