### ISSUE TITLE
$(...).fireModal is not a function

### ISSUE THREAD

**Issue by Amystherdam** [stisla/stisla#214]
I am trying to create a button with the attribute "data-confirm".

`<button class="btn btn-danger trigger--fire-modal-1" data-confirm="Realy?|Do you want to continue?" data-confirm-yes="alert('Deleted :)');">Delete</button>`

But when I reload the page the scripts.js file throws the error `Uncaught TypeError: me.fireModal is not a function`

And if I add the bootstrap-modal.js file it throws the error  `Uncaught TypeError: $(....).fireModal is not a function`

I downloaded the project yesterday by making a git clone

If I just leave the modal() method instead of fireModal() it breaks the modal presentation

**Comment by Amystherdam** [comment]
Yes!

**Comment by syahid246** [comment]
Paste the code script.
Example :
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
```
Maybe because the script tag order is not correct 😶.

**Comment by saurabh-thoughti** [comment]
@Amystherdam

**Comment by Acemint** [comment]
I was able to reproduce this bug by placing the bootstrap-modal.js dependency above stisla.js like so:
```
<script src="./src/assets/js/page/bootstrap-modal.js"></script>
<script src="./src/assets/js/stisla.js"></script>
```

To solve it, just put the bootstrap modal dependency below stisla
```
<script src="./src/assets/js/stisla.js"></script>
<script src="./src/assets/js/page/bootstrap-modal.js"></script>
```

The reason is because bootstrap-model.js method call $(...).fireModal depends on stisla.js definition of fireModal(). So changing the order helps the rendered to know that fireModal is defined in stisla.js
