### ISSUE TITLE
class was-validated not working when using select2

### ISSUE THREAD

**Issue by crescent1** [stisla/stisla#217]
Hi, class "was-validated" doesn't work properly when added with select2. It does show the feedback text, but not with border color.

this pic example.
![select2-validation](https://user-images.githubusercontent.com/8374604/145150657-e02f3e72-6c0d-410c-a4d8-f1e84cc03c38.PNG)

thanks.

**Comment by syahid246** [comment]
See in this [link](https://stackoverflow.com/a/54510152/14809952)
![image](https://user-images.githubusercontent.com/73120669/151590449-1261b473-a163-4d49-8857-77118450af35.png)
