### ISSUE TITLE
Badges radius

### ISSUE THREAD

**Issue by zeraferrari** [stisla/stisla#218]
excuse me sir,, but how to change badges into square badge in stisla ? that badges class "badge badge-info" have much radius. how if i not want using that radius ? just like badge square was i want

**Comment by syahid246** [comment]
How about this :
```html
<span class="badge badge-secondary rounded-0">Square Badge</span>
```

Stisla is use Bootstrap 4.1.3.
You can visit [Bootstrap 4.1 documentation](https://getbootstrap.com/docs/4.1/getting-started/introduction/)

About `border-radius` :
[https://getbootstrap.com/docs/4.1/utilities/borders/#border-radius](https://getbootstrap.com/docs/4.1/utilities/borders/#border-radius)
