### ISSUE TITLE
Error Yarn Install

### ISSUE THREAD

**Issue by XCOD33** [stisla/stisla#228]
error E:\stisla\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\stisla\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe E:\stisla\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\stisla\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.15.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\stisla\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\stisla\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\stisla\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\stisla\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\stisla\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\stisla\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\stisla\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\stisla\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\stisla\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\stisla\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\stisla\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\stisla\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python310\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\stisla\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\stisla\node_modules\node-sass
gyp ERR! node -v v16.15.1

**Comment by zuramai** [comment]
It should be fixed by [dbe9cb3](https://github.com/stisla/stisla/commit/dbe9cb3f1eac177fd75fcc73cc2c3535618e52ed), can you try again?
