### ISSUE TITLE
Closing other open sidebar dropdowns

### ISSUE THREAD

**Issue by th-thomas** [stisla/stisla#235]
Hi,

First of all, thank you for this great project. 👍 

Here is the problem.
When I click on a dropdown in the sidebar menu, it unwraps the corresponding dropdown menu with children links. Cool.
However, I would like _only one_ sidebar dropdown menu open (unwrapped) at a time.

How could I accomplish that ?

I guess it's not that complicated, but I am a real noob in JS, that's why I'm asking for your help.

Thanks :)

**Comment by zuramai** [comment]
Hi @th-thomas,

To achieve the "only open one sidebar dropdown at a time", you can do this trick:

https://github.com/stisla/stisla/blob/da1ddd2ac7bcd694defab4bf4c7d4ffc31a64ba0/assets/js/scripts.js#L112-L116

The use of code above is to open the clicked menu. Add some code above it, here's the step: 
 
1. Select all '.dropdown-menu' elements
2. Loop through the elements, and close all the dropdown by doing jQuery slideUp `element.slideUp(500)`
3. Open the clicked element (like the above code)
