### ISSUE TITLE
Isntal stisla

### ISSUE THREAD

**Issue by morgankaka** [stisla/stisla#239]
Hai, bagaimana cara menginstal template admin stisla ke CI3,  saya ingin memasang stilsla yang bagan general dashboard saja

Sudah di panggil pake base_url  di assetnya tapi tampilan tidak sempurna.

**Comment by rwaddin** [comment]
tinggal disesuaikan kan aja, 
- buat controller
- htmlnya pindah /views
- panggil html yang di view lewat controller
