### ISSUE TITLE
sound player with icon and apache eCharts not responsive

### ISSUE THREAD

**Issue by fasteddys** [stisla/stisla#241]
Hello, I am very excited and been digging into it, I saw your doc page and was referring to the album. and I was trying to display songs/album using this opensource https://wavesurfer-js.org/ but the filter and songs are not responsive/overlapping

I was originally trying something like this with [filters](https://tinyurl.com/56htrr2b), but I am not able to achieve it.

![image](https://user-images.githubusercontent.com/96149622/186954442-fa5667cd-3151-4455-a2d9-481eba90a655.png)

**Comment by zuramai** [comment]
Can you give a screenshot/gif of how the unresponsive might looks like?
