### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by Ashurali** [stisla/stisla#255]
The documentation website is down. 
Is it possible to get a copy or a file to look at the examples and documentation?

**Comment by rwaddin** [comment]
https://demo.getstisla.com/

> The documentation website is down. Is it possible to get a copy or a file to look at the examples and documentation?

**Comment by aryomuzakki** [comment]
@Ashurali 

found the docs here

https://docs.getstisla.com/

and repo here

https://github.com/stisla/docs

**Comment by Ashurali** [comment]
Awesome thank you.
Yes this link works, I was referring to this link which is what clicking on documentation on the front page of this github leads to.

https://getstisla.com/docs
