### ISSUE TITLE
Not responsive in layout-top-navigation.html

### ISSUE THREAD

**Issue by SunDi3yansyah** [stisla/stisla#26]

**Comment by nauvalazhar** [comment]
What do you mean about "not responsive"? Can you attach a screenshot?

**Comment by SunDi3yansyah** [comment]
sorry, I mean the menu icon on the left is not the same as the other pages :smile: 

![photo6312326191440308402](https://user-images.githubusercontent.com/3952281/53341188-7c237e80-393d-11e9-82de-00339128d3da.jpg)

**Comment by alexandre-pereira** [comment]
Issue still here.

**Comment by lilouch** [comment]
When we dezoom the layout does not change and does not fit into the screen. Any help ?
