### ISSUE TITLE
Write a better documentation

### ISSUE THREAD

**Issue by nauvalazhar** [stisla/stisla#28]
Write the documentation properly. Write how to use each component, such as adding navbar, section, sidebar, and others.

**Comment by nauvalazhar** [comment]
Maybe someone wants to work here?

**Comment by mlazuardy** [comment]
lemme handle it @nauvalazhar

**Comment by nauvalazhar** [comment]
Ok, cool. Go to [this repo](https://github.com/stisla/docs).

**Comment by nauvalazhar** [comment]
@mlazuardy Can you finish in the near future? We will release version 2.3 in the next few days.

**Comment by mlazuardy** [comment]
what must be finished first? the 2.3 version? @nauvalazhar

**Comment by nauvalazhar** [comment]
Yep, version 2.3. I have completed several tasks, one of which is the "Upgrade Guides". You can write documentation about Gulp, Yarn, CLI usage or how to use components, such as Navbar, Section, Sidebar and so on. Because the least documented part is managing the component.

**Comment by nauvalazhar** [comment]
Hi, @mlazuardy. Are you working on this?

**Comment by mlazuardy** [comment]
@mlazuardy yeah, but i can only do it at night, do you need me to work quickly?

**Comment by nauvalazhar** [comment]
Ok, good. No, I just want to confirm with you.

**Comment by mlazuardy** [comment]
okay, i can spend more time in this thursday @nauvalazhar

**Comment by mlazuardy** [comment]
the documentation will structured like bootstrap. So, component view first and then the html code/or any related code @nauvalazhar

**Comment by nauvalazhar** [comment]
Ok good. It will be better than before. 🚀

**Comment by nauvalazhar** [comment]
Hi, @mlazuardy. How is it going?

**Comment by mlazuardy** [comment]
My laptop charger was broken, I was only able to do the documentation again today @nauvalazhar

**Comment by mlazuardy** [comment]
I just worked on about 20% of the documentation, sorry if it's a little slow @nauvalazhar

**Comment by nauvalazhar** [comment]
Okay, will wait.
