### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by andysteel** [stisla/stisla#38]
Is There any tutorial on how to change the theme colors ?

**Comment by nauvalazhar** [comment]
Please check `the _variables.scss` file located in the `sources/scss` folder.

**Comment by brianwachira** [comment]
I haven't worked with SCSS before. Anyway I have gone through the content and I have seen that `sources/scss/override/_variable.scss` has the main colors. I have tried changing the colors but nothing seems to change. After coming to this issue, I have realized I need to compile the scss files after changing. How do I do that? and after compiling, now that there are other css files, how will it reflect there?

**Comment by brianwachira** [comment]
> I haven't worked with SCSS before. Anyway I have gone through the content and I have seen that `sources/scss/override/_variable.scss` has the main colors. I have tried changing the colors but nothing seems to change. After coming to this issue, I have realized I need to compile the scss files after changing. How do I do that? and after compiling, now that there are other css files, how will it reflect there?

Update : I am following this tutorial. Let's see how it goes [(https://webdesign.tutsplus.com/tutorials/watch-and-compile-sass-in-five-quick-steps--cms-28275)]

**Comment by brianwachira** [comment]
> Please check `the _variables.scss` file located in the `sources/scss` folder.

Is there a way to use linear-gradient( ) in variables.scss? I keep getting the error 

`Error: argument `$color` of `lighten($color, $amount)` must be a color\n        on line 32 of scss/_variable.scss, in function `lighten`\n        from line 32 of scss/_variable.scss, in function `color_lighten`\n        from line 79 of scss/_mixin.scss, in mixin `form-control`\n        from line 5 of scss/override/_form.scss\n        from line 63 of scss/style.scss\n>> \t@return lighten(map-get($colors, $key), $amount);\n\n`

I have searched for an understandable solution on the net but I haven't found any.

**Comment by zuramai** [comment]
@brianwachira you should apply the linear gradient directly to the class. The Bootstrap's variables will be passed into mixin that is only can process a color, not linear-gradient.
