### ISSUE TITLE
sidebar caret

### ISSUE THREAD

**Issue by Matromag** [stisla/stisla#39]
In the elements of sidebar the icon is always "caret-down". 
It's better use "caret-right" when a element isn't active.

**Comment by nauvalazhar** [comment]
When using `caret-right` it doesn't identify that the menu below is a dropdown. It might be suitable if the menu hovers next to it (like a sidebar when toggled).

**Comment by Matromag** [comment]
All others dashboard use caret-right when dropdown is closed and caret-down when is opened

**Comment by nauvalazhar** [comment]
Hm, can you give me an example?

**Comment by Matromag** [comment]
![Immagine](https://user-images.githubusercontent.com/48549328/54416886-f7887c80-4700-11e9-9498-be297f5278c8.png)

**Comment by nauvalazhar** [comment]
I think the better thing is to make it `caret-down`, then when the dropdown is open, it will become `caret-up`. That would make more sense.
