### ISSUE TITLE
sidebar-mini init page

### ISSUE THREAD

**Issue by ricardocarrer** [stisla/stisla#40]
Hi! 

When a page with the sidebar-mini and does a toggle to show, the scrool goes wrong.

Add the below line 134:

sidebar_nicescroll.remove ();
sidebar_nicescroll = null;

Correct? 

tks

**Comment by ricardocarrer** [comment]
Did not work :(

**Comment by nauvalazhar** [comment]
And why you closed this issue? 😆

**Comment by ricardocarrer** [comment]
When it starts with the sidebar-mini it gets sidebar_nicescroll active and does not add the tooltip in the single menu. When it expands, the sidebar_nicescroll gets broken, it does not stay the same width as the sidebar. I tried to make some adjustments, but I did not succeed.

Sorry for my english (google translator)

**Comment by ricardocarrer** [comment]
I tried to find a solution to contribute, but without success! :(

Reopen issue!

Congratulations on the initiative, I found Stisla excellent!


De: Muhamad Nauval Azhar <notifications@github.com>
Responder para: stisla/stisla <reply@reply.github.com>
Data: sexta-feira, 15 de março de 2019 03:09
Para: stisla/stisla <stisla@noreply.github.com>
Cc: Ricardo Carrer <ricardocarrer@gmail.com>, State change <state_change@noreply.github.com>
Assunto: Re: [stisla/stisla] sidebar-mini init page (#40)


And why you closed this issue? 😆

**Comment by ricardocarrer** [comment]
Hi! 

I think it was!


Transform in function for add tooltip single menu:
//add RC
  var add_tooltip_sidebar_mini = function() {
    $(".main-sidebar .sidebar-menu > li").each(function() {
      let me = $(this);

      if(me.find('> .dropdown-menu').length) {
        me.find('> .dropdown-menu').hide();
        me.find('> .dropdown-menu').prepend('<li class="dropdown-title pt-3">'+ me.find('> a').text() +'</li>');
      }else{
        me.find('> a').attr('data-toggle', 'tooltip');
        me.find('> a').attr('data-original-title', me.find('> a').text());
        $("[data-toggle='tooltip']").tooltip({
          placement: 'right'
        });
      }
    });
  }

in else toggle_sidebar_mini:

}else{
      body.addClass('sidebar-mini');
      body.removeClass('sidebar-show');
      sidebar_nicescroll.remove();
      sidebar_nicescroll = null;

      //add RC
      add_tooltip_sidebar_mini();
    }


in toggleLayout, add other else if:

//Add RC
}else if($("body").hasClass('sidebar-mini')){ 
        add_tooltip_sidebar_mini(); //transform in function
        if(sidebar_nicescroll != null) {
          sidebar_nicescroll.remove();
        }
 }else{
        update_sidebar_nicescroll();
      }

**Comment by nauvalazhar** [comment]
Hm, if you want the `sidebar-mini` as an initial sidebar. Simply you can trigger the toggle button with JavaScript.
```
$('[data-toggle="sidebar"]').click();
```

**Comment by ricardocarrer** [comment]
With trigger click add in custom.js:

$('[data-toggle="sidebar"]').trigger('click');


[cid:image001.png@01D4E61E.32F06650]

De: Muhamad Nauval Azhar <notifications@github.com>
Responder para: stisla/stisla <reply@reply.github.com>
Data: sexta-feira, 15 de março de 2019 21:42
Para: stisla/stisla <stisla@noreply.github.com>
Cc: Ricardo Carrer <ricardocarrer@gmail.com>, State change <state_change@noreply.github.com>
Assunto: Re: [stisla/stisla] sidebar-mini init page (#40)


Hm, if you want the sidebar-mini as an initial sidebar. Simply you can trigger the toggle button with JavaScript.

$('[data-toggle="sidebar"]').click();

**Comment by MarcusMann** [comment]
@ricardocarrer  i implemented this. I'm Await an issue be approved.

Please look for this: https://github.com/stisla/docs/issues/5

**Comment by ricardocarrer** [comment]
Thanks man.

😊

De: Marcus Mann <notifications@github.com>
Responder para: stisla/stisla <reply@reply.github.com>
Data: quarta-feira, 3 de abril de 2019 16:09
Para: stisla/stisla <stisla@noreply.github.com>
Cc: Ricardo Carrer <ricardocarrer@gmail.com>, Mention <mention@noreply.github.com>
Assunto: Re: [stisla/stisla] sidebar-mini init page (#40)


@ricardocarrer<https://github.com/ricardocarrer> i implemented this. I'm Await an issue be approved.

Please look for this: stisla/docs#5<https://github.com/stisla/docs/issues/5>

**Comment by MarcusMann** [comment]
This was implemented , now, await the pr https://github.com/stisla/docs/pull/6 . :)
