### ISSUE TITLE
Integrate bootstrap-datepicker?

### ISSUE THREAD

**Issue by Matromag** [stisla/stisla#42]
https://github.com/uxsolutions/bootstrap-datepicker

**Comment by nauvalazhar** [comment]
We've integrated datepicker. Please check this out.
https://demo.getstisla.com/forms-advanced-form.html

**Comment by Matromag** [comment]
you use daterangepicker, bootstrap-datepicker is much better!

**Comment by nauvalazhar** [comment]
Hm, I'll think about it

**Comment by Matromag** [comment]
Thanks!

**Comment by jyehahaha** [comment]
hi nauvalazhar, 

i still have problem to integrate with datetimepicker. can u help?

**Comment by nauvalazhar** [comment]
> hi nauvalazhar,
> 
> i still have problem to integrate with datetimepicker. can u help?

Hi, what's the problem?

**Comment by jyehahaha** [comment]
Hi Nauval,

Im trying to use date picker using below code but the its dont fire the
datetimepicker. and also in the* forms-advanced-forms.js *dont have
datepicker

form:
 <div class="form-group">
     <label>Date Picker</label>
    <input type="text" class="form-control datepicker">
</div>

* forms-advanced-forms.js:*
 "use strict";

var cleavePN = new Cleave('.phone-number', {
    phone: true,
    phoneRegionCode: 'us'
});
var cleaveC = new Cleave('.currency', {
    numeral: true,
    numeralThousandsGroupStyle: 'thousand'
});
var cleavePC = new Cleave('.purchase-code', {
    delimiter: '-',
    blocks: [4, 4, 4, 4],
    uppercase: true
});
var cleaveI = new Cleave('.invoice-input', {
    prefix: 'INV',
    delimiter: '-',
    blocks: [10],
    uppercase: true
});
var cleaveD = new Cleave('.datemask', {
    date: true,
    datePattern: ['Y', 'm', 'd']
});
var cc_last_type;
var cleaveCC = new Cleave('.creditcard', {
    creditCard: true,
    onCreditCardTypeChanged: function (type) {
        if (type !== 'unknown') {
            if (type === 'amex') {
                type = 'americanexpress';
            } else if (type === 'mastercard') {
                type = 'mastercard';
            } else if (type === 'visa') {
                type = 'visa';
            } else if (type === 'diners') {
                type = 'dinersclub';
            } else if (type === 'discover') {
                type = 'discover';
            } else if (type === 'jcb') {
                type = 'jcb';
            }
            $(".creditcard").removeClass(cc_last_type);
            $(".creditcard").addClass(type);
            cc_last_type = type;
        }
    }
});

$(".pwstrength").pwstrength();

$('.daterange-cus').daterangepicker({
    locale: { format: 'YYYY-MM-DD' },
    drops: 'down',
    opens: 'right'
});
$('.daterange-btn').daterangepicker({
    ranges: {
        'Today': [moment(), moment()],
        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1,
'days')],
        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
        'This Month': [moment().startOf('month'), moment().endOf('month')],
        'Last Month': [moment().subtract(1, 'month').startOf('month'),
moment().subtract(1, 'month').endOf('month')]
    },
    startDate: moment().subtract(29, 'days'),
    endDate: moment()
}, function (start, end) {
    $('.daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' +
end.format('MMMM D, YYYY'))
});

$(".colorpickerinput").colorpicker({
    format: 'hex',
    component: '.input-group-append',
});
$(".inputtags").tagsinput('items');


sorry if u dont understand my english.

regards,
Naziha

**Comment by nauvalazhar** [comment]
Is there any errors in your browser console?

**Comment by jyehahaha** [comment]
i got below error when inspect. From my console, there is no error.

[image: image.png]

Thank you

Regards,
Naziha

**Comment by andresuntoro** [comment]
Hi @nauvalazhar , when I try to call the datepicker() function in javascript. Its function is not running. Does stisla not include the datepicker function?

// // // // // // // // // // // // // // // //

Halo @nauvalazhar , apa fungsi datepicker() di Stisla gak ada ? Soalnya waktu dipakai tidak bisa. 

Terima kasih.

![datepicker](https://user-images.githubusercontent.com/32894340/60807987-69ee0280-a1b1-11e9-9ee6-71ac080f2932.JPG)

**Comment by nauvalazhar** [comment]
> Hi @nauvalazhar , when I try to call the datepicker() function in javascript. Its function is not running. Does stisla not include the datepicker function?
> 
> // // // // // // // // // // // // // // // //
> 
> Halo @nauvalazhar , apa fungsi datepicker() di Stisla gak ada ? Soalnya waktu dipakai tidak bisa.
> 
> Terima kasih.
> 
> ![datepicker](https://user-images.githubusercontent.com/32894340/60807987-69ee0280-a1b1-11e9-9ee6-71ac080f2932.JPG)

Hi, it looks like the Datepicker JS isn't imported correctly.
