### ISSUE TITLE
template scss not changing btn outline color and some other class

### ISSUE THREAD

**Issue by senzlord** [stisla/stisla#44]
I try to change All Button Color, but for .btn .btn-outline-{color} classes secondary info warning an danger still using old color.

**Comment by nauvalazhar** [comment]
Please show me your code.

**Comment by senzlord** [comment]
_variable.scss
```
$colors: (
  primary:    		#ff6161,
  secondary:      #ff9b61,
  success:        #00ff2a,
  info:           #00aeff,
  warning:        #ff26ac,
  danger:         #ff0d00,
  light:          #d8d8d8,
  grey:  		      #868e96,
  whitesmoke:     #f7f9f9,
  dark:       		#0a0b0c,
  muted:          #98a6ad,
  body:           #fafdfb,
  font:           #6c757d,
  fontdark:       #34395e,
  white:          #ffffff
);
```

**Comment by nauvalazhar** [comment]
Do you recompile SCSS files?

**Comment by senzlord** [comment]
Yes... Do i missing something ?

**Comment by nauvalazhar** [comment]
Possibly the size on the icon is `important`. So, it can't be resized through classes that are in Font Awesome.

**Comment by nauvalazhar** [comment]
It's possible that the class has `!Important` so it is not overridden.

**Comment by senzlord** [comment]
So what should i use to compile the scss ? 
I was using Ruby Sass 3.7.3 .

**Comment by nauvalazhar** [comment]
Try to rewrite some classes that don't change color.
