### ISSUE TITLE
Fontawesome Sizing

### ISSUE THREAD

**Issue by tryfatur** [stisla/stisla#45]
How to use fontawesome sizing on Stisla, such `fas fa-download fa-5x`. Because it seems like not working. Thank you !

**Comment by nauvalazhar** [comment]
Possibly the size on the icon is important. So, it can't be resized through classes that are in Font Awesome.

**Comment by tryfatur** [comment]
So, is there any solution for fixing this?

**Comment by nauvalazhar** [comment]
Just create your own custom class for resizing the Font Awesome icon.
```
.my-fa {
  font-size: 40px !important;
}
```

**Comment by lkloon123** [comment]
this issue is caused by this line, can it possible be removed?

https://github.com/stisla/stisla/blob/3049d2a92a9d4d58a7937da9ef157b674f2bf246/sources/scss/theme/_misc.scss#L184-L186

**Comment by nauvalazhar** [comment]
I think if you remove those lines, it will cause all the icon sizes to change. Before making a pull request, try it on your local project first.

**Comment by lkloon123** [comment]
i did commented out for my project, din realize any problem, mayb its for some component that i dint use

**Comment by tryfatur** [comment]
I should try this

**Comment by tryfatur** [comment]
> i did commented out for my project, din realize any problem, mayb its for some component that i dint use

I should try this

**Comment by Blaztix** [comment]
Same here, I remove that lines
