### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by mehmetmenengec** [stisla/stisla#47]
Hi,

At the content area of a blank page, ".main-content" area is fitted to screen height by the code in row 107 of "scripts.js". According to top nav and footer, minus value should be at least 108 instead of 95. In the other way  the page is overlowing down if there is no content.

_**Original Value:**_ 
```
$(".main-content").css({
    minHeight: $(window).outerHeight() - 95
})
```

_**Fixed:**_
```
$(".main-content").css({
    minHeight: $(window).outerHeight() - 108
})
```

Thank you.

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. It's better if you make a pull request 😄

**Comment by mehmetmenengec** [comment]
Hi again,
I have made a pull request.
Thank you too for this great project! ☺️

**Comment by nauvalazhar** [comment]
#48
