### ISSUE TITLE
Why scroll is not responsive ? when scroll on sidebar main content scrolled too

### ISSUE THREAD

**Issue by natsirasrafi** [stisla/stisla#50]

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Can you give me the details?

**Comment by manusiakemos** [comment]
yes. when i scroll the sidebar. the main content is scrolled too

**Comment by manusiakemos** [comment]
not scrolling in the scrollbar

**Comment by manusiakemos** [comment]
when i scroll the sidebar with the scrollbar it works perfectly. but you know it's no simple when i can scroll with 2 fingers with my mac

**Comment by prdip** [comment]
You can solve it by adding CSS to this div

<div class="main-sidebar sidebar-style-2" style="overflow-y:scroll!important; ">
                <aside id="sidebar-wrapper">

> **overflow-y:scroll !important;** 

Also i have customize scrollbar using this css

> .main-sidebar{ 
>   overflow-y: scroll !important;  
> }
> 
> .main-sidebar::-webkit-scrollbar {
>   width: 5px;
> } 
> .main-sidebar::-webkit-scrollbar-track {
>   box-shadow: inset 0 0 2px #1c4354; 
>   border-radius: 10px;
> } 
> .main-sidebar::-webkit-scrollbar-thumb {
>   background: #42a002; 
>   border-radius: 10px;
> } 
> .main-sidebar::-webkit-scrollbar-thumb:hover {
>   background: #009eb3; 
> }
