### ISSUE TITLE
sidebar badges (counters)

### ISSUE THREAD

**Issue by khanzadimahdi** [stisla/stisla#52]
i need to use badges in sidebar to show numbers, but it makes the sidebar nested menus deformed.

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Can you give me a screenshot and your markup?

**Comment by nachoaguirre** [comment]
Hi! I managed to use badges in sidebar, just adding a div after the span with menu text, example:
<li>
<a class="nav-link" href="#">
<i class="fas fa-calendar-alt"></i>
<span>De la semana</span>
<div class="badge badge-info">4</div>
</a>
</li>

Using <span> for badge causes the badges displays as block (wide), using <i> for badge causes italic text in badge, so <div> works great for me.

Regards

<img width="241" alt="Captura de Pantalla 2020-01-07 a la(s) 20 04 03" src="https://user-images.githubusercontent.com/52148018/71936670-e8d7ee00-3188-11ea-91bf-e88ed40cce0b.png">

**Comment by nauvalazhar** [comment]
Thanks, @nachoaguirre. I'll close this issue.
