### ISSUE TITLE
Add Laravel Support

### ISSUE THREAD

**Issue by ManojKiranA** [stisla/stisla#56]
I am  wondering while  reading the readme docs  [Integrates](https://github.com/stisla/stisla#integrates). And i have planned to Contribute it for the laravel stisla

I want to clearly know the following thinks

- Do i need to develop in the Package way or Application (laravel)

- And Second thing Will You Add my name to the Contributors list

**Comment by nauvalazhar** [comment]
Hi, it's great if you will make integration with Laravel.

- I think it's better if you make a skeleton or package.
- Add your own package list in the `readme.md` file and your name will be automatically registered

**Comment by ManojKiranA** [comment]
ok sir When i was free i will start working on it thanks for the quick reply

**Comment by nauvalazhar** [comment]
FYI, someone has made it, but you can also make it or maybe collaborate.
https://github.com/rehmatworks/stisla-laravel

**Comment by ManojKiranA** [comment]
> FYI, someone has made it, but you can also make it or maybe collaborate.
> https://github.com/rehmatworks/stisla-laravel

I think he has made a **boilerplate** project of laravel with stisla and spatie-permission

But I am About to Convert the **Html to Blade(Laravel)**

**Comment by cyberhck** [comment]
FYI, we're working on new version of this, it'd be so much appreciated if you can help us out, @nauvalazhar is a bit busy and I've not that much experience with UI, once we're done, it'll be so easy for you to implement this in laravel :)

**Comment by ManojKiranA** [comment]
> FYI, we're working on new version of this, it'd be so much appreciated if you can help us out, @nauvalazhar is a bit busy and I've not that much experience with UI, once we're done, it'll be so easy for you to implement this in laravel :)

I was feeling so sad sir because.I dont Know about design or ui part. I will choose the bootstrap themes and use it my project sir.But I have Started Integrating the Theme with laravel

**Comment by ManojKiranA** [comment]
I have Created the initial Version

[stisla-bootstrap-laravel](https://github.com/ManojKiranA/stisla-bootstrap-laravel)
