### ISSUE TITLE
Refactoring the entire project. What do you think?

### ISSUE THREAD

**Issue by nauvalazhar** [stisla/stisla#58]
Hi.
As I mentioned before, I have a plan to refactoring the entire infrastructure of this project.

Behind this idea, I feel Stisla is just too boring to be a admin template, moreover everyone who uses Stisla will have the same layout, colors and components. And I also don't want to depend on Bootstrap and jQuery. 

Recently I was interested in TailwindCSS, maybe we can use it as a base framework; with it, we can make some basic elements such as Card, Alert, Nav, etc. TailwindCSS is a utility-first framework so that it can reduce custom classes and use utility classes such as `.p-5` (to add `padding`) instead.

I also plan to break the template into several parts, at least:
- **Element**
This is the core part of the template, here are the basic elements such as buttons, alerts, navigation, typography and more.

- **Layout**
You need to specify the layout you want to use for the current project interface.
![Layout](https://user-images.githubusercontent.com/14899175/55937078-44a93100-5c62-11e9-9202-fa7891392d8a.png)

- **Section**
Next, specify a section. This section is easy, usually only the title, subtitle, description and post meta (author, published date).
![Section](https://user-images.githubusercontent.com/14899175/55937088-4b37a880-5c62-11e9-8f20-683c6ff89327.png)

- **Block**
Blocks are pre-designed components that consist of elements and have a specific purpose. Each block consists of HTML, SCSS, JavaScript API (if any).
![Block](https://user-images.githubusercontent.com/14899175/55937076-44a93100-5c62-11e9-96af-cd1529a8c81c.png)
---

Each of the above parts is customizable (color, sequence of elements, etc). Will be better to have a code that can be adapted to the front-end framework, such as ReactJS (JSX), Vue Component, Angular and so on. Each of the parts above has its own documentation page and versioning, so, I think every part will have a public repository.

Besides that, I also think each part can be installed via Yarn/NPM. So, SCSS and JavaScript are automatically installed in the current project folder.

For example:
```
# layout
stisla use layout/style-1

# block
stisla add component/twitter-card
```

As such, this won't be the template admin only. You can also create templates for landing pages or others.

This will not delete the admin templates that currently exist. We will recreate the admin template with new concepts and architecture.

What do you think about this?

Thank you

**Comment by cyberhck** [comment]
I love the idea, when we do this, I can create react components in parallel, at the end we should be able to recreate this admin template both in react and normal html/css.

And let's make whatever we can very modular, so if we need a card component, then it'll have card.scss, if it depends on something, it should mark it as a dependency.

Let's start by breaking down components into very small piece, build them and later patch things up.

I'd say if we can do it gradually like by targeting pages, I'd go for blank page at first, once the blank page is done, login page etc, that'd work great.

Would you be open to creating a slack workspace for this so we can discuss easier? I'll help you in keeping things modular and implementing in react side of things, someone else can take vuejs and angularjs implementation.

For me, multiple theme support is a huge plus, let's make a list of things we'd like to do first, then we can think about how we can achieve it.

At last I want to be able to get core.css, and should be able to slap in any theme, (dark/light according to user's preference), but I don't want to include other information than colors in theme files.

**Comment by nauvalazhar** [comment]
Cool! I will be back soon after work.

**Comment by nauvalazhar** [comment]
I've been created the Slack workspace: https://join.slack.com/t/stisla/shared_invite/enQtNTk4OTcxOTk5NjMzLTVmNzA3NGFmNmY1ZTM1NzBkZWFiNTg5YjQ3Y2VhZGRhNjZjNDliODFkMzMxZmVjM2ViZDExYzQ1MzU2MDc3ODg

**Comment by alexandre-pereira** [comment]
Please use Bootstrap. More and more devs are multi-tasks on projects, and they don't have time to learn front integration CSS rules just for ONE design. You can do thoses blocks components, but just use bootstrap 4 as a base and no Tailwind. What the adventages of it over Bootstrap?

**Comment by cyberhck** [comment]
With bootstrap you're stuck with using jQuery which we're trying to avoid, if you really want to stick with bootstrap, you can keep using the current version of stisla, when we get rid of jQuery stuff, then all components will play nicely with bunch of frontend frameworks like React, Angular, Vue etc.

**Comment by RenetalAdmin** [comment]
Not sure you guys considered to use Bulma which works very well with frontend frameworks?

**Comment by coderabsolute** [comment]
Are you guys considering to use Bulma which works well with frontend frameworks?

**Comment by nauvalazhar** [comment]
> Are you guys considering to use Bulma which works well with frontend frameworks?

Bulma is an awesome framework. But, overwriting Bulma's default style doesn't take a short time.

**Comment by nauvalazhar** [comment]
Hi, I started designing a design system for the new Stisla. We have many tasks to do, before starting a new template/framework, we can talk about design first. Then, we talk about the framework we will use, such as TailwindCSS or we start everything from scratch.

The point of this refractor, I want to build an infrastructure that can be easily adapted to the JavaScript framework, can be adapted to brand users, customizable, component-rich, pre-built pages and functionality.

![image](https://user-images.githubusercontent.com/14899175/60243710-0aefda00-98e3-11e9-8181-d0b4f7726de0.png)

**Comment by cyberhck** [comment]
let's write everything from scratch please, by that we can get very flexible/performant code out, if I want to strip all the media queries to another file and do mobile first, then I can,

My initial idea was like this:
we do mobile first design, so phones will get `core.css` and `theme.css` (in some case maybe the user of this framework want to have just `core.css` where he combines both theme and core in same file

but the desktops and tablets will get one more file called `responsive.css`, this way phone will only get the smallest bundle size.

btw, what are you using for designing that?

**Comment by cyberhck** [comment]
Hey, let's hit pause on writing actual CSS, looks like they're dropping jQuery in bootstrap which means our problems will be solved, let's see if they do it properly or not.

**Comment by nauvalazhar** [comment]
Yeah. Bootstrap 5 will come without jQuery. But, I still don't know of any other major changes.

**Comment by coderabsolute** [comment]
If we wait for them to release the Bootstrap5 (hopefully without the jQuery), not sure how long we will be waiting? It may take a year or a few months, we still don't know - just my thought.

**Comment by cyberhck** [comment]
it's not hopefully without jQuery:
https://github.com/twbs/bootstrap/blob/4b3d2635f34a36742f6f3ab0f969a80b0c21a0ef/package.json#L104-L107

It's only requirement will be pooper.js which is actually a peer dependency.

Yes, I'm all good with using figma for designing, but if jQuery will be removed anyway, I think the existing figma UI can be ported to v5 just in case, where people can still use it when we are still doing working on new version.

**Comment by coderabsolute** [comment]
Do you guys want to arrange the kick-off meeting and have then the meeting every now and then? ;)

**Comment by liyilike** [comment]
Wait till bootstrap 5 comes out, because now I just want to be stable, there will be less work to do after the revision.

**Comment by coderabsolute** [comment]
Read somewhere that Alpha of Bootstrap 5 will be released this year, but the stable version will be released only in 2020. We can consider going ahead with Bulma (not a bad choice) but we need to do more customization I think.

**Comment by nauvalazhar** [comment]
Bulma has a good concept about customizing: https://bulma.io/documentation/customize/concepts.

**Comment by coderabsolute** [comment]
@nauvalazhar If we all think that Bulma is good enough for us to achieve what we want to achieve then let's go ahead with Bulma and don't even need to divert our thinking towards the Bootstrap. Anyway,  just a thought...

**Comment by nauvalazhar** [comment]
Basically, I don't depend too much on Bootstrap or Bulma. I'm currently thinking about architecture or methodology that we can use to write better CSS framework.

**Comment by nauvalazhar** [comment]
Good discussion, guys. Sorry, I'm late, the last month I was sick, and in the future, I'm undergoing recovery. I think it will take a long time and a lot of effort to refactor it. If I have some free time, maybe I'll fix and improvise some parts of Stisla and of course, write better documentation. Until now Bootstrap 4 is still getting updates and adding some new components, that is my reason, right now, I prefer to maintain Stisla until the time comes to refactor it. I thank you for caring about Stisla and for giving me an extraordinary perspective in this discussion.

For now, I'll close this issue.

**Comment by cyberhck** [comment]
That works, please note that bootstrap 5 is in the works, which means, as long as we can use that with bs5, we can use it with react/angular/vue/markojs/whatever
