### ISSUE TITLE
Integrate in existing Symfony 4 project

### ISSUE THREAD

**Issue by Err0r404** [stisla/stisla#60]
Hi,

I'm really not experienced with frontend so I hope this is the right place to ask my question.

Is there any documentation to add the whole Stisla theme to an existing (Symfony 4) project?
Maybe something like `yarn add stisla`?
Don't know if that can help you to answer but here is how to add bootstrap 4 to Symfony 4 : https://symfony.com/doc/current/frontend/encore/bootstrap.html

Currently I have downloaded the release and put everything in my assets folder, then require everything I need in a js files but I'm not sure this the right way to do it because I have some errors...

**Comment by cyberhck** [comment]
Yes, you can do that way, I'm not aware of this being published to npm, although if you're interested, we're working on a new version at #58 and are looking for help, that'll be published to npm.
