### ISSUE TITLE
Firemodal validation

### ISSUE THREAD

**Issue by nandhini-ecrubit** [stisla/stisla#61]
Hi there! I'm new to this setup. Please tell me how to do a form validation in Firemodal function

**Comment by nauvalazhar** [comment]
Hi, what form validation do you mean?

**Comment by nandhini-ecrubit** [comment]
In Modal Login form validation

**Comment by nauvalazhar** [comment]
Do you want to validate the form in "Firemodal"?

**Comment by nandhini-ecrubit** [comment]
yes. I want to validate the form in `.fireModal()`

**Comment by nauvalazhar** [comment]
You can validate the form fields with `submit` callback. https://docs.getstisla.com/#/en/2.2.0/javascript/modal

**Comment by nandhini-ecrubit** [comment]
I've added a basic validation. the first alert shows twice, when i click OK the form submitted without validating other fields. Below is the code i used. Please tell me how to proceed further
`$("#modal-add-expense").fireModal({
  title: 'Add Expense',
  footerClass: 'bg-whitesmoke',
  body: $("#modal-add-expense-part"),
  autoFocus: false,
  onFormSubmit:function(modal) {
      var ex_date = $('#add_ex_date').val();
      var ex_item = $('#add_ex_item').val();
      var ex_amt  = $('#add_ex_amt').val();
      if (ex_date == '') {
        alert('Please Selet date!');
        return false;
      }
      else if (ex_item == '') {
        alert('Please provide Expense Item!');
        return false;
      }
      else if(ex_amt == ''){
        alert('Please provide Expense Amount!');
        return false;
      }
  },
});`
