### ISSUE TITLE
Sidebar state

### ISSUE THREAD

**Issue by faiztriguna** [stisla/stisla#62]
How to remember sidebar last state ? If on one page the sidebar is closed, then when I open another page, I need the sidebar state remain close. How do I do it ?

**Comment by faiztriguna** [comment]
I found an approach from [here](https://github.com/ColorlibHQ/AdminLTE/issues/896#issuecomment-264723101), and use it successfully on my project.

Case closed !

**Comment by wsupajirakit** [comment]
@faiztriguna 
I put this code on my index.html on <body> but not working

  <script>
    (function () {
      if (Boolean(sessionStorage.getItem('sidebar-toggle-collapsed'))) {
        var body = document.getElementsByTagName('body')[0];
        body.className = body.className + ' sidebar-collapse';
      }
    })();
  </script>

  ...

  <script>
    // Click handler can be added latter, after jQuery is loaded...
    $('.sidebar-toggle').click(function(event) {
      event.preventDefault();
      if (Boolean(sessionStorage.getItem('sidebar-toggle-collapsed'))) {
        sessionStorage.setItem('sidebar-toggle-collapsed', '');
      } else {
        sessionStorage.setItem('sidebar-toggle-collapsed', '1');
      }
    });
  </script>

**Comment by daverussell13** [comment]
> @faiztriguna I put this code on my index.html under tag < body > but not working
> 
> ```
>   <script>
>     (function () {
>       if (Boolean(sessionStorage.getItem('sidebar-toggle-collapsed'))) {
>         var body = document.getElementsByTagName('body')[0];
>         body.className = body.className + ' sidebar-collapse';
>       }
>     })();
>   </script>
> 
>   ...
> 
>   <script>
>     // Click handler can be added latter, after jQuery is loaded...
>     $('.sidebar-toggle').click(function(event) {
>       event.preventDefault();
>       if (Boolean(sessionStorage.getItem('sidebar-toggle-collapsed'))) {
>         sessionStorage.setItem('sidebar-toggle-collapsed', '');
>       } else {
>         sessionStorage.setItem('sidebar-toggle-collapsed', '1');
>       }
>     });
>   </script>
> ```

you shouls use sidebar-mini instead of sidebar-collapse on body classname and target the toggle with attribute data-toggle='sidebar' instead of using .sidebar-toggle
