### ISSUE TITLE
Multilevel submenus spacing and icons

### ISSUE THREAD

**Issue by leandro-almeida** [stisla/stisla#63]
Hi, first of all, thanks for taking your time on this project! Its awesome!

I have a question/feature request maybe.
In the demo pages, i couldnt see an example of multileve submenus. Also, the submenus doesnt have an icon. It would be great.

In my project i'm facing this problem:

![chrome_2019-05-29_08-40-18](https://user-images.githubusercontent.com/1966285/58555294-76b12b00-81ef-11e9-921f-5c407cca76ee.jpg)

When the items in menu have a larger text, it breaks down and add a big space/line height. How can we solve this?

Thank you very much!

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Maybe you can use CSS `text-overflow: ellipsis;`.

**Comment by mjanowskiiskzy** [comment]
Hi, if you want to get multiple dropdowns in sidebar menu  (without unnessesary closing) just overwrite sidebar_dropdown function in your additional script file (custom.js). My modified function is below.  Menu can be styled with overwriting Stisla css with you additional file.

`var sidebar_dropdown = function() {
    if($(".main-sidebar").length) {
      $(".main-sidebar").niceScroll(sidebar_nicescroll_opts);
      sidebar_nicescroll = $(".main-sidebar").getNiceScroll();
      $(".main-sidebar .sidebar-menu li a.has-dropdown").off('click').on('click', function() {
        var me = $(this);
        var parentLi = me.parent();
        var parentUl = parentLi.parent();
        if(!parentLi.hasClass('active')){
                parentLi.addClass('active');
                $(parentUl).find('li.active > .dropdown-menu').not(me).slideUp(300, function() {
                    $(parentUl).find('li.active').not(parentLi).removeClass('active');  
                        me.parent().find('> .dropdown-menu').slideDown(300, function() {
                      return false;
                    });
                    return false;
                });
                update_sidebar_nicescroll();
        }
        else{
            parentLi.removeClass('active');
            parentLi.find('> .dropdown-menu').slideUp(300, function() {
              return false;
            });
            update_sidebar_nicescroll();
        }
        return false;
      });

      $('.main-sidebar .sidebar-menu li.active > .dropdown-menu').slideDown(500, function() {
        update_sidebar_nicescroll();
        return false;
      });
    }
  }
  sidebar_dropdown();`

**Comment by leandro-almeida** [comment]
Hi, thanks for replying. I actually modified the css, more like a workaround (i'm not a webdesigner).
The css modified was style.css (v 2.2), added `line-height: initial;`

`
.main-sidebar .sidebar-menu li ul.dropdown-menu li a {
            line-height: initial;
            color: #868e96;
            height: 35px;
            padding-left: 65px;
            font-weight: 400;
}
`

Result was:
![image](https://user-images.githubusercontent.com/1966285/59273273-2ba30900-8c2e-11e9-9c9f-947d1b83196f.png)

Its not perfect, but its better.

**Comment by nauvalazhar** [comment]
Is ok to close this issue?
