### ISSUE TITLE
rich text editors

### ISSUE THREAD

**Issue by FRONTXIE** [stisla/stisla#64]
Hello, I am from China, I am very happy to use the template, but I have not been able to find rich text editors, can you help me?

**Comment by nauvalazhar** [comment]
Hi, is there an error in the DevTools console?

**Comment by FRONTXIE** [comment]
Hello, I am very happy to receive your reply so soon. I have successfully solved this problem. It turns out that the js/css that access the foreign website in the source code has timed out. I found a reference to the rich text editor on your demo site and downloaded the icon source file. Thank you again for your reply.



------------------ 原始邮件 ------------------
发件人: "Muhamad Nauval Azhar"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 下午5:23
收件人: "stisla/stisla"<stisla@noreply.github.com>; 
抄送: "FRONT"<FRONT_XIE@foxmail.com>; "Author"<author@noreply.github.com>; 
主题: Re: [stisla/stisla] rich text editors (#64)




Hi, is there an error in the DevTools console?
