### ISSUE TITLE
sidebar-menu nav-item dropdown always open

### ISSUE THREAD

**Issue by cesarlopes** [stisla/stisla#67]
Hello,

In the side bar menu always an na-iitem is open, even clicking on the top to close it, can I allow all items to be closed?

**Comment by pedrazadixon** [comment]
I fix this temporally remplacing the new _sidebar_dropdown_ function (from master) in scripts.js with the old function (in last release).

You can find this line in scripts.js and replace the content inside brackets: 

> var sidebar_dropdown = function() { ... }

If anyone has a better solution let me know.

**Comment by Jewinn** [comment]
@pedrazadixon there is a problem in a new version that the active page in active menu is getting inactive after looking at any one of dropdowns. share the solution if you have any..
