### ISSUE TITLE
Active class on li not working when open another dropdown-menu (ul)

### ISSUE THREAD

**Issue by wsupajirakit** [stisla/stisla#70]
Active class on li not working when open another dropdown-menu (ul)

1. It's active 

![Screen Shot 2562-07-06 at 10 34 43](https://user-images.githubusercontent.com/24472014/60751018-078ed980-9fda-11e9-88b0-e9134fc4d5d3.png)

2. when open another dropdown and back to first dropdown class active is missing
![Screen Shot 2562-07-06 at 10 34 38](https://user-images.githubusercontent.com/24472014/60751025-16758c00-9fda-11e9-8d53-c1d7b1274581.png)

**Comment by dubnm** [comment]
@nauvalazhar I believe I am seeing this same issue. From what I have understood, this is compiled using nunjucks? However, I cannot get it working on the client side either. I can see that on the Stisla demo site that this functionality is working:
![image](https://user-images.githubusercontent.com/3620552/64923486-d718a800-d79f-11e9-88a1-d410797a8ea4.png)

but not while using Browsersync:
![image](https://user-images.githubusercontent.com/3620552/64923500-029b9280-d7a0-11e9-9e3e-989b15ce4fc4.png)

How do we handle this on the client side to show the active menu item?
![image](https://user-images.githubusercontent.com/3620552/64923452-9e78ce80-d79f-11e9-97e4-ab30e08aa128.png)

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Stisla has 3 sidebars option that you can't find on the documentation: default, `.sidebar-style-1` and `.sidebar-style-2`.

![image](https://user-images.githubusercontent.com/14899175/64930708-8071a380-d85d-11e9-90c9-1dfc38e0543e.png)

What you see on the demo page is `sidebar-style-2`. I think that's a bug in the default sidebar layout.

One more thing. I just realized the demo page isn't the same as the one on GitHub (not updated).

**Comment by dubnm** [comment]
Ah, ok... That makes sense now. You should be able to close this issue as I believe this is what @wsupajirakit was referring to as well. Thank you!

**Comment by mrizkihidayat66** [comment]
```
document.addEventListener('DOMContentLoaded', function () {
    // Get the current URL path
    var currentPath = window.location.pathname;

    // Get all the sidebar links
    var sidebarLinks = document.querySelectorAll('#sidebar-wrapper .nav-link');

    sidebarLinks.forEach(function (link) {
        // Get href attribute and clean it if necessary (remove any query parameters or fragments)
        var linkHref = new URL(link.getAttribute('href'), window.location.origin).pathname;

        // Compare each link's href with the current path
        if (linkHref === currentPath) {
            // Add active class to the parent li element
            var parentLi = link.closest('li');
            if (parentLi) {
                parentLi.classList.add('active');

                // If the li is within a dropdown, make sure to open it
                var dropdown = parentLi.closest('.dropdown');
                if (dropdown) {
                    dropdown.classList.add('active');
                }
            }
        }
    });
});
```

Place this code in _assets/js/custom.js_
