### ISSUE TITLE
About color

### ISSUE THREAD

**Issue by jokin1999** [stisla/stisla#75]
Don't u guys think that the colours like green are too light to read in Stisla?
The green button, which uses `.btn-success` class, with white texts, is hard to read on screens.

**Comment by zkmark** [comment]
edita el **success: #63ed7a**,  dentro de sources->scss->_variable.scss por tu color
-
edit **success: # 63ed7a,** within sources-> scss -> _ variable.scss for your color

**Comment by jokin1999** [comment]
Thank u :)
