### ISSUE TITLE
TextArea doesn't  change size.

### ISSUE THREAD

**Issue by AlexTselikas** [stisla/stisla#79]
Hello,
I am not able to change the size of TextArea,neither by increasing the row size or by dragging down the corner.It doesn't work on the demo  website either.If i don't apply the `class="form-control' `it works.Is that intended behaviour?
Best regards

**Comment by nauvalazhar** [comment]
Hi, you can use the CSS `height` property and put the `!important` rule in it.
```
.my-textarea {
  height: 100px !important;
}
```

**Comment by AlexTselikas** [comment]
Hi @nauvalazhar ,
I did find it earlier but forgot to post it here.
Thank you for your help.
Best Regards
