### ISSUE TITLE
facing difficulty in multi auth

### ISSUE THREAD

**Issue by komalwath** [stisla/stisla#80]
hii,
while logging in by using different users credentials I am getting admin.dashboard all the time.i want different different panels or dashboards for different different users.I am unable to write web.php file for this problem,I tried all possible ways though but still i have not solved it

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. I think your problem is about PHP and it's not relevant if you post this issue in this repo. Stisla is just an HTML template, not PHP framework :)
