### ISSUE TITLE
Modal dialogs blend into the background (using datatable)

### ISSUE THREAD

**Issue by oimtrust** [stisla/stisla#81]
I have a problem when I want to display a modal dialog from datatable, the modal merge with the background. It looks like this:

![image](https://user-images.githubusercontent.com/9985668/63206284-e2fb4680-c0db-11e9-9490-6c05cb11454f.png)

Source code :
**Button :**
```
<button class="btn btn-icon btn-sm btn-danger" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-trash"></i></button>
```

**Modal Dialog :**
```
<div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
       <div class="modal-dialog" role="document">
             <div class="modal-content">
                   <div class="modal-header">
                            <h5 class="modal-title">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                    </div>
                   <div class="modal-body">
                       <p>Modal body text goes here.</p>
                   </div>
                   <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
          </div>
</div>
```

Please help @nauvalazhar and all friends, thank's

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. I think the problem is about HTML structure, you need to put modal structure in a higher structure. For example,
```
<body>
  <div class="modal">...</div>
  ...
  <div class="section ...
```

**Comment by oimtrust** [comment]
Solved. Thanks a lot. :-D

**Comment by dkreider** [comment]
You can also fix this issue by removing the `position: relative` style from the `section` class. Below is a link to the code I'm referring to.

https://github.com/stisla/stisla/blob/9aaf4ec3dddab1ddbc4ef86952054d1b64e188d0/sources/scss/theme/_section.scss#L1-L3

**Comment by crescent1** [comment]
You can add `position: static !important` : 

`.custom-section {
    position: static !important;
}`

than add to your html : 

`<section class="section custom-section">...</section>`
