### ISSUE TITLE
Demo Page / Login 2 template link

### ISSUE THREAD

**Issue by tariksisbacak** [stisla/stisla#82]
Hi,

Your demo page does not include some updates.

Auth > Login 2

**Comment by nauvalazhar** [comment]
Hi, can you give me more details about this?

**Comment by tariksisbacak** [comment]
> Hi, can you give me more details about this?

Login 2 template does not exist on demo page sidebar menu

**Comment by nauvalazhar** [comment]
Oh, I see. If you want, you can make a pull request.

**Comment by tariksisbacak** [comment]
Of course. i want to do:) Thanks
