### ISSUE TITLE
Running yarn stisla-dev

### ISSUE THREAD

**Issue by oddovid** [stisla/stisla#83]
Hi, I'm using node.js v12.0.0, npm v6.9.0, and yarn v1.17.3. I ran "yarn stisla-dev", I got this result:

```
$ yarn install --prod
info No lockfile found.
[1/4] Resolving packages...
warning nicescroll@3.7.4: Please use official npm package at https://www.npmjs.com/package/jquery.nicescroll
warning gulp-imagemin > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-imagemin > imagemin-optipng > optipng-bin > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 316.75s.
```
Is this normal? how to generate `dist` folder? thnks

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Does it work? I mean, does it run in a browser?

**Comment by GerryGe** [comment]
How to build the dist folder?

**Comment by nauvalazhar** [comment]
> How to build the dist folder?

Just run the `gulp` command.

**Comment by permanar** [comment]
> > How to build the dist folder?
> 
> Just run the `gulp` command.

@nauvalazhar 
I am sorry if this is a stupid question but, whenever I ran `gulp` (which is the same as `yarn dev`), it just simply starting a new `localhost` server. I have no `dist` folder or the `build` or whatever I expected to be the final HTML ready to use. Am I missing something?

**Comment by nauvalazhar** [comment]
> > > How to build the dist folder?
> > 
> > 
> > Just run the `gulp` command.
> 
> @nauvalazhar
> I am sorry if this is a stupid question but, whenever I ran `gulp` (which is the same as `yarn dev`), it just simply starting a new `localhost` server. I have no `dist` folder or the `build` or whatever I expected to be the final HTML ready to use. Am I missing something?

Is there an error message?

**Comment by permanar** [comment]
```
PS D:\Code\Template\stisla> yarn dev
yarn run v1.9.4
$ gulp
[22:35:56] Using gulpfile D:\Code\Template\stisla\gulpfile.js
[22:35:56] Starting 'default'...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
[Browsersync] Access URLs:
 ---------------------------------------------------------
       Local: http://localhost:8080/pages/index.html
    External: http://192.168.197.225:8080/pages/index.html
 ---------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ---------------------------------------------------------
[Browsersync] Serving files from: ./
```
That's all I got.  And this is my folder list.
```
PS D:\Code\Template\stisla> dir


    Directory: D:\Code\Template\stisla


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/10/2020   8:05 PM                .github
d-----        1/10/2020   8:05 PM                assets
d-----        1/10/2020   8:05 PM                dev
d-----        1/10/2020   9:18 PM                node_modules
d-----        1/10/2020   9:00 PM                pages
d-----        1/10/2020   8:05 PM                sources
-a----        1/10/2020   8:05 PM            783 .all-contributorsrc
-a----        1/10/2020   8:05 PM            231 .editorconfig
-a----        1/10/2020   8:05 PM            407 .gitignore
-a----        1/10/2020   8:05 PM           3430 CODE_OF_CONDUCT.md
-a----        1/10/2020   8:05 PM            886 CONTRIBUTING.md
-a----        1/10/2020   9:23 PM           1200 debug.log
-a----        1/10/2020   8:05 PM           4537 gulpfile.js
-a----        1/10/2020   8:05 PM           1084 LICENSE
-a----        1/10/2020   8:35 PM           2420 package.json
-a----        1/10/2020   8:05 PM           5147 README.md
-a----        1/10/2020   9:16 PM         254279 yarn-error.log
-a----        1/10/2020   8:39 PM         235545 yarn.lock
```

**Comment by nauvalazhar** [comment]
Did you try `yarn upgrade`?

**Comment by permanar** [comment]
No. Because I think there's no correlation among these. Let me try it then.

**Comment by permanar** [comment]
```
$ gulp
[22:55:47] Using gulpfile D:\Code\Template\stisla\gulpfile.js
[22:55:47] Starting 'default'...
[Browsersync] Access URLs:
 ---------------------------------------------------------
       Local: http://localhost:8080/pages/index.html
    External: http://192.168.197.225:8080/pages/index.html
 ---------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ---------------------------------------------------------
[Browsersync] Serving files from: ./
```
No hope. But glad the error was fixed. But not with the main issue.

**Comment by Jewinn** [comment]
@permanar I'm also facing the same issue, i'm also not getting compiled output and at the same time when I save my scss changes it does not watching and updating on browsersync, so I'm not able to see live development as well as not able to export it.. I need some help for that.!

**Comment by permanar** [comment]
@Jewinn Ikr? But I didn't get replied as you can see.

**Comment by ramadhandont** [comment]
error Couldn't find package "@sindresorhus/is@^0.7.0" required by "got@^8.3.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.

E:\stisla>dir
 Volume in drive E is YENNY
 Volume Serial Number is 907B-8921

 Directory of E:\stisla

08/06/2020  05:17 PM    <DIR>          .
08/06/2020  05:17 PM    <DIR>          ..
08/06/2020  05:19 PM             5,868 .all-contributorsrc
08/06/2020  05:19 PM               231 .editorconfig
08/06/2020  05:19 PM    <DIR>          .github
08/06/2020  05:19 PM               407 .gitignore
08/06/2020  05:19 PM             3,430 CODE_OF_CONDUCT.md
08/06/2020  05:19 PM               886 CONTRIBUTING.md
08/06/2020  05:19 PM             1,084 LICENSE
08/06/2020  05:19 PM            11,186 README.md
08/06/2020  05:19 PM    <DIR>          assets
08/06/2020  05:19 PM    <DIR>          dev
08/06/2020  05:19 PM             4,537 gulpfile.js
08/06/2020  05:19 PM             2,449 package.json
08/06/2020  05:19 PM    <DIR>          pages
08/06/2020  05:19 PM    <DIR>          sources
08/06/2020  05:19 PM           314,222 yarn.lock
08/06/2020  05:20 PM           333,571 yarn-error.log
              11 File(s)        677,871 bytes
               7 Dir(s)   4,582,064,128 bytes free


please help error

**Comment by Michael-Francalanci** [comment]
Same here, there is no dist folder

**Comment by aliansyahh** [comment]
how to fix error? 
C:\Users\User\Desktop\template\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\User\Desktop\template\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\User\Desktop\template\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\User\\Desktop\\template\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\User\Desktop\template\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\User\Desktop\template\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (C:\Users\User\Desktop\template\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\Desktop\\template\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\User\Desktop\template\node_modules\node-sass
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by ulfahputribisba** [comment]
> how to fix error?
> C:\Users\User\Desktop\template\node_modules\node-sass: Command failed.
> Exit code: 1
> Command: node scripts/build.js
> Arguments:
> Directory: C:\Users\User\Desktop\template\node_modules\node-sass
> Output:
> Building: C:\Program Files\nodejs\node.exe C:\Users\User\Desktop\template\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [
> gyp verb cli 'C:\Program Files\nodejs\node.exe',
> gyp verb cli 'C:\Users\User\Desktop\template\node_modules\node-gyp\bin\node-gyp.js',
> gyp verb cli 'rebuild',
> gyp verb cli '--verbose',
> gyp verb cli '--libsass_ext=',
> gyp verb cli '--libsass_cflags=',
> gyp verb cli '--libsass_ldflags=',
> gyp verb cli '--libsass_library='
> gyp verb cli ]
> gyp info using node-gyp@3.8.0
> gyp info using node@14.16.0 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` failed Error: not found: python2
> gyp verb `which` failed at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
> gyp verb `which` failed at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
> gyp verb `which` failed at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:183:21)
> gyp verb `which` failed python2 Error: not found: python2
> gyp verb `which` failed at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
> gyp verb `which` failed at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
> gyp verb `which` failed at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:183:21) {
> gyp verb `which` failed code: 'ENOENT'
> gyp verb `which` failed }
> gyp verb check python checking for Python executable "python" in the PATH
> gyp verb `which` failed Error: not found: python
> gyp verb `which` failed at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
> gyp verb `which` failed at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
> gyp verb `which` failed at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:183:21)
> gyp verb `which` failed python Error: not found: python
> gyp verb `which` failed at getNotFoundError (C:\Users\User\Desktop\template\node_modules\which\which.js:13:12)
> gyp verb `which` failed at F (C:\Users\User\Desktop\template\node_modules\which\which.js:68:19)
> gyp verb `which` failed at E (C:\Users\User\Desktop\template\node_modules\which\which.js:80:29)
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\which\which.js:89:16
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\index.js:42:5
> gyp verb `which` failed at C:\Users\User\Desktop\template\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed at FSReqCallback.oncomplete (fs.js:183:21) {
> gyp verb `which` failed code: 'ENOENT'
> gyp verb `which` failed }
> gyp verb could not find "python". checking python launcher
> gyp verb could not find "python". guessing location
> gyp verb ensuring that file exists: C:\Python27\python.exe
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack at PythonFinder.failNoPython (C:\Users\User\Desktop\template\node_modules\node-gyp\lib\configure.js:484:19)
> gyp ERR! stack at PythonFinder. (C:\Users\User\Desktop\template\node_modules\node-gyp\lib\configure.js:509:16)
> gyp ERR! stack at callback (C:\Users\User\Desktop\template\node_modules\graceful-fs\polyfills.js:295:20)
> gyp ERR! stack at FSReqCallback.oncomplete (fs.js:183:21)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\User\Desktop\template\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd C:\Users\User\Desktop\template\node_modules\node-sass
> gyp ERR! node -v v14.16.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> Build failed with error code: 1
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

same here! I got this message when I run `yarn` command

**Comment by michail1982** [comment]
Error says you doesnt have python2 and python-gyp. Install it 😉

**Comment by fzn0x** [comment]
Hi guys, late to the party.

Please use the development steps below, make sure **gulp** is installed

```
yarn
yarn dist
yarn dev
```
