### ISSUE TITLE
What do you think about Stisla?

### ISSUE THREAD

**Issue by nauvalazhar** [stisla/stisla#85]
Hi, so far Stisla has almost reached 1000 stars on GitHub. I know that we still need to improve some parts and the most important is documentation. But, personally, this is a new achievement for me in terms of OSS.

However, I'm glad so far Stisla has helped other developers ease their work - in terms of the user interface.

Previously, I had a discourse to refactor the whole project, but that needs further study. Moreover, Bootstrap is already embedded in the heads of developers today. Some other reasons that made me "hold on" to Bootstrap as a Stisla base.

To be honest, I'm waiting for Bootstrap 5 to start updating this template. However, there is still no news when Bootstrap 5 will be released.

So what do you think about Stisla, so far? I mean, do you have criticism, suggestions or requests for me to consider in the next update? In fact, many people have problems with NPM - when they try to run Stisla for the first time.

I will write down all of your suggestions and consider them for updates next time.

Thank you <3

**Comment by PierreSchwang** [comment]
Hi,

first of all thank you for the nice web template and the work you put into it.
I intend to use it for a project, but don't want to use such large assets (~50MB in this case), because it increases the load time incredibly, especially in slow networks.
Maybe a lightweight edition would be cool, also for other users. With significantly less assets, but also less functionality (graphs, etc).

**Comment by nauvalazhar** [comment]
> Hi,
> 
> first of all thank you for the nice web template and the work you put into it.
> I intend to use it for a project, but don't want to use such large assets (~50MB in this case), because it increases the load time incredibly, especially in slow networks.
> Maybe a lightweight edition would be cool, also for other users. With significantly less assets, but also less functionality (graphs, etc).

Looks like we need a lite and full version, right?

**Comment by cyberhck** [comment]
Actually, all we need to do is modularize the code, let's say if someone wants to use a button, just use button.scss and that's all :) then it'll keep the size to a minimum.

**Comment by PierreSchwang** [comment]
> 
> 
> > Hi,
> > first of all thank you for the nice web template and the work you put into it.
> > I intend to use it for a project, but don't want to use such large assets (~50MB in this case), because it increases the load time incredibly, especially in slow networks.
> > Maybe a lightweight edition would be cool, also for other users. With significantly less assets, but also less functionality (graphs, etc).
> 
> Looks like we need a lite and full version, right?

Exactly, that would be cool.

> 
> 
> Actually, all we need to do is modularize the code, let's say if someone wants to use a button, just use button.scss and that's all :) then it'll keep the size to a minimum.

That sounds good too, but I was more bothered by the Modules folder.
The CSS folder is about 300KB, the Modules folder about 50MB. And I don't necessarily know which modules I can just delete, or if any modules depend on other modules, which then have other dependencies...
(I didn't find anything in the documentation, but would be cool if that works.)

**Comment by nauvalazhar** [comment]
> Actually, all we need to do is modularize the code, let's say if someone wants to use a button, just use button.scss and that's all :) then it'll keep the size to a minimum.

I think the same thing! Each component/element/kit has its SCSS & JS file.

**Comment by nauvalazhar** [comment]
> > > Hi,
> > > first of all thank you for the nice web template and the work you put into it.
> > > I intend to use it for a project, but don't want to use such large assets (~50MB in this case), because it increases the load time incredibly, especially in slow networks.
> > > Maybe a lightweight edition would be cool, also for other users. With significantly less assets, but also less functionality (graphs, etc).
> > 
> > 
> > Looks like we need a lite and full version, right?
> 
> Exactly, that would be cool.
> 
> > Actually, all we need to do is modularize the code, let's say if someone wants to use a button, just use button.scss and that's all :) then it'll keep the size to a minimum.
> 
> That sounds good too, but I was more bothered by the Modules folder.
> The CSS folder is about 300KB, the Modules folder about 50MB. And I don't necessarily know which modules I can just delete, or if any modules depend on other modules, which then have other dependencies...
> (I didn't find anything in the documentation, but would be cool if that works.)

Yes, I admit that the structure of Stisla now really sucks. It really forces you to load everything that even you don't need.

In the next update, I will change the structure to follow other components to be more modular – load when you need them.

**Comment by PierreSchwang** [comment]
> 
> 
> > > > Hi,
> > > > first of all thank you for the nice web template and the work you put into it.
> > > > I intend to use it for a project, but don't want to use such large assets (~50MB in this case), because it increases the load time incredibly, especially in slow networks.
> > > > Maybe a lightweight edition would be cool, also for other users. With significantly less assets, but also less functionality (graphs, etc).
> > > 
> > > 
> > > Looks like we need a lite and full version, right?
> > 
> > 
> > Exactly, that would be cool.
> > > Actually, all we need to do is modularize the code, let's say if someone wants to use a button, just use button.scss and that's all :) then it'll keep the size to a minimum.
> > 
> > 
> > That sounds good too, but I was more bothered by the Modules folder.
> > The CSS folder is about 300KB, the Modules folder about 50MB. And I don't necessarily know which modules I can just delete, or if any modules depend on other modules, which then have other dependencies...
> > (I didn't find anything in the documentation, but would be cool if that works.)
> 
> Yes, I admit that the structure of Stisla now really sucks. It really forces you to load everything that even you don't need.
> 
> In the next update, I will change the structure to follow other components to be more modular – load when you need them.

That sounds great! Ideally, this should also make updating easier if everything does not depend on each other.

**Comment by dubnm** [comment]
Thank you for all your work on this project. I am currently testing and considering using it as part of my next project. I know you already mentioned it, but the documentation needs some serious work. If I do end up using this template, I would love to give back to the project by updating the documentation. Thanks again!

**Comment by callumb** [comment]
A version that doesn't need the install of NPM, yarn etc... Not everyone uses these to build sites.

**Comment by akunbeben** [comment]
Webpack and stisla is a robust stack. I love it. Thanks, mas Nauval for your hard work to make this great web template🚀

**Comment by rizkyyangpalsu** [comment]
Any idea for migrating stisla to bootstrap 5?

**Comment by nauvalazhar** [comment]
> Any idea for migrating stisla to bootstrap 5?

Yep, but I can't work full-time for it.

**Comment by nauvalazhar** [comment]
I need your opinion here #203
