### ISSUE TITLE
Do you use Stisla? Show off here!

### ISSUE THREAD

**Issue by nauvalazhar** [stisla/stisla#86]
<3

**Comment by liyicool** [comment]
He's an invincible, beautiful and amazing template. It's the best template I've ever seen in the world.

**Comment by ranzeplay** [comment]
The best css template. Better than Bootstrap.

**Comment by fajarsusilo07** [comment]
mantap

**Comment by joaovdiasb** [comment]
![image](https://user-images.githubusercontent.com/51106311/68154775-05f10600-ff27-11e9-903c-6c9d4de420aa.png)

**Comment by joaovdiasb** [comment]
![image](https://user-images.githubusercontent.com/51106311/68154813-1c975d00-ff27-11e9-885c-fe85de408f5d.png)
![image](https://user-images.githubusercontent.com/51106311/68154840-2e790000-ff27-11e9-87a6-739784026543.png)
at work

**Comment by mariocalin** [comment]
I am developing a prototype for an open source project I am currenty developing at work. I hope it will become the favorite option and we will use the template!

**Comment by jokin1999** [comment]
![image](https://user-images.githubusercontent.com/16080182/70809330-8cd5b000-1dfc-11ea-9a55-054bbcb04c38.png)

**Comment by tarikhagustia** [comment]
hi @nauvalazhar i think for show off part need to add to readme.md section, how do you think?

**Comment by nauvalazhar** [comment]
> hi @nauvalazhar i think for show off part need to add to readme.md section, how do you think?

Your PR has been merged.

**Comment by nauvalazhar** [comment]
Hi, @jokin1999 and @joaovdiasb, can you add your project to `readme.md`?

**Comment by jokin1999** [comment]
> Hi, @jokin1999 and @joaovdiasb, can you add your project to `readme.md`?

Sorry, my project has not finished yet and it will be deployed as an unpublic programme.

**Comment by RealistikDash** [comment]
![image](https://user-images.githubusercontent.com/36131887/77761232-0144ff80-7038-11ea-896b-a47bcc4e19d7.png)
Still learning but stisla made my project look actually good.

**Comment by lucky988** [comment]
i use stisla in mobile phone but the css design is not view is just icon and structure ? what i can do for better understanding it?

**Comment by aacassandra** [comment]
saya bangga dengan stisla, ini adalah admin template favorite. semoga stisla bisa menjadi lebih GILA lagi

**Comment by fajarwz** [comment]
![image](https://user-images.githubusercontent.com/39845286/104081155-6b453300-525f-11eb-83dd-9a18ca6703f5.png)
![2](https://user-images.githubusercontent.com/39845286/104081188-acd5de00-525f-11eb-9119-053dfd657e3b.jpeg)

Keren bang templatenya, saya pake di projek saya.
Cool template! i use this on my project [ROOMING](https://github.com/fajarwz/rooming)
