### ISSUE TITLE
Why is *.lock in the git ignore file?

### ISSUE THREAD

**Issue by dubnm** [stisla/stisla#87]
Hello! Is there a specific reason that `*.lock` is part of the `.gitignore`? According to Yarn themselves, they state the lockfiles should always be committed: ((https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/))

Let me know if you would like me to send in a pull request removing this line from the `.gitignore`. Thank you for your hard work on this project!

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. I think that's my bad. Could you make a pull request, please?

**Comment by muhammad-ihsan** [comment]
@dubnm @nauvalazhar should we close this issue according [this pull](https://github.com/stisla/stisla/commit/f434ec986c34cc0862d5a031dc8e23d8a1f410f1) already fixed?

**Comment by nauvalazhar** [comment]
> @dubnm @nauvalazhar should we close this issue according [this pull](https://github.com/stisla/stisla/commit/f434ec986c34cc0862d5a031dc8e23d8a1f410f1) already fixed?

Ah, yes. Thank you for reminding me!
