### ISSUE TITLE
sizing not work in select html object

### ISSUE THREAD

**Issue by johan-gates27** [stisla/stisla#93]
hai @nauvalazhar , 

txt to build this template, i really like it

i wanna create form with many fields, so i must to set all html object as small view
this is my form
![image](https://user-images.githubusercontent.com/55593058/65366615-84803580-dc50-11e9-8076-a93646c29581.png)

This is screenshot of bootstrap-form.html,
![image](https://user-images.githubusercontent.com/55593058/65366497-f8b9d980-dc4e-11e9-8069-5c6d4315936b.png)

form-control-sm and form-control-lg class is doesn't work in select html object
please help me

thank u

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. I think there's the `!important` keyword. So try to create your own custom class for this case and add the `!important` keyword – just dirty quick solution.

**Comment by johan-gates27** [comment]
i was try to add my class + !important value at the custom.css and this is not work
but this problems has been solved by put css reverance in custom.js 

$('select.form-control.form-control-sm').css({"height": "2rem","padding":" 5px 5px"});
$('select.form-control.form-control-lg').css({"height": "3rem","padding":" 5px 5px"});

thx for your support
