### ISSUE TITLE
Can we import it from a CDN like bootstrap

### ISSUE THREAD

**Issue by ranzeplay** [stisla/stisla#94]
Like this:
`<link rel="stylesheet" href="a cdn website">`

Or download it as a product. like stisla.min.css and stisla.min.js or stisla.css and stisla.js.
To make the development easier.

**Comment by nauvalazhar** [comment]
Of course, you can. But, you need to upload Stisla assets to CDN.

**Comment by ranzeplay** [comment]
The official CDN. Import everything from it.

**Comment by nauvalazhar** [comment]
I don't understand your point

**Comment by ranzeplay** [comment]
Like this:
We can import the full stisla css and js file with all dependencies from a certain website like 
```
<link rel="stylesheet" href="cdn.getstisla.com/stisla-full.css">
<script src="cdn.getstisla.com/stisla-full.css"></script>
```
It can import as a single css without bootstrap.

**Comment by nauvalazhar** [comment]
For now, you can't do that.
