### ISSUE TITLE
The modal mask is at the upper layer

### ISSUE THREAD

**Issue by ranzeplay** [stisla/stisla#95]
I used this in the HTML
```
<span class="btn btn-link" style="margin: 0 auto; text-align: center; color: blue" data-toggle="modal" data-target="#addEmployeeModal">Add employee</span>

<div class="modal fade" id="addEmployeeModal" tabindex="-1" role="dialog" aria-labelledby="addEmployeeModalLabel" aria-hidden="true">


```

But the result is that the mask is at the upper layer so I can't do anything when the modal opened but refresh.

**Comment by nauvalazhar** [comment]
Attach the screenshot, please.

**Comment by ranzeplay** [comment]
![批注 2019-09-22 151002](https://user-images.githubusercontent.com/43675876/65383662-284e0c00-dd4b-11e9-837b-e4e9be24fd79.png)
![批注 2019-09-22 151121](https://user-images.githubusercontent.com/43675876/65383679-54698d00-dd4b-11e9-82d0-acf86d827211.png)
![批注 2019-09-22 151135](https://user-images.githubusercontent.com/43675876/65383680-54698d00-dd4b-11e9-8e50-55ee48c759d5.png)
![批注 2019-09-22 151149](https://user-images.githubusercontent.com/43675876/65383681-55022380-dd4b-11e9-828a-9222f81e68d5.png)
Here are the screenshots. It seems the problem about the mask which disables the operations with background

**Comment by nauvalazhar** [comment]
Please refer to this issue: #81
