### ISSUE TITLE
Bagaimana menggunakan event hide.bs.modal pada firemodal

### ISSUE THREAD

**Issue by fajarsusilo07** [stisla/stisla#96]
**Saya** ingin membuat modal tapi menggunakan firemodal .
jika tanpa firemodal **saya bisa** menggunakan kode `$("#id-modal).on('hide.bs.modal", function(){
// kode });` tapi bagimana jika ingin menggunakan firemodal ?
bagaimana cara mendapatkan #id-modal yang di buat firemodal

**Comment by cyberhck** [comment]
please use english
