### ISSUE TITLE
Menu Levels

### ISSUE THREAD

**Issue by garbinmarcelo** [stisla/stisla#97]
Hello,
Would you have any menu demo with different levels?

Thank's

**Comment by nauvalazhar** [comment]
Hi, what do you mean about "different levels"? Could you explain more detail to me?

**Comment by marcelogarbin** [comment]
> Hi, what do you mean about "different levels"? Could you explain more detail to me?

Like in this picture...

![image](https://user-images.githubusercontent.com/9335588/65775377-70d44380-e116-11e9-9c59-12ce31967fe3.png)

**Comment by nauvalazhar** [comment]
Ah, we don't have it on the demo page. But, I think you can do something like that with my template. I'll be back with an example.

**Comment by bilsou** [comment]
Any news on this ?
