### ISSUE TITLE
installation problem in laravel

### ISSUE THREAD

**Issue by ProfessionalWebProgrammer** [stisla/stisla#98]
npm i stisla
npm WARN deprecated nicescroll@3.7.4: Please use official npm package at https://www.npmjs.com/package/jquery.nicescroll
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     path\npm-cache\_logs\2019-10-02T06_41_13_654Z-debug.log

**Comment by nauvalazhar** [comment]
Use Yarn instead of NPM
