### ISSUE TITLE
Module not found: Error: Can't resolve 'stisla'  and running  yarn stisla-dev command

### ISSUE THREAD

**Issue by ProfessionalWebProgrammer** [stisla/stisla#99]
require("stisla")
Module not found: Error: Can't resolve 'stisla' in 'D:\laravel\laravel(6.0.2)\resources\js'

 yarn stisla-dev
yarn run v1.17.3
error Command "stisla-dev" not found.

**Comment by nauvalazhar** [comment]
Can you explain more details what do you want to do?

**Comment by ProfessionalWebProgrammer** [comment]
window.$ = window.jQuery = require('jquery');
require('bootstrap');
require('admin-lte');
require('datatables.net-dt');
require('datatables.net-responsive-dt');
require('bootstrap-datepicker');
require('bootstrap-timepicker');


This is configuration file for laravel npm package, after installing a npm package in laravel just need to require this package

if you want to more details what i want, please see this tutorial:
https://www.youtube.com/watch?v=9Ipu43Qo-C0&t=237s

i just want to add this stisla admin template like this way

**Comment by nauvalazhar** [comment]
Oh, you can't do that. Stisla isn't a package on NPM. So, you can import Stisla assets with the `<link` tag and the `<script` tag.
